#pragma config(Sensor, S2,     lightSensor1,   sensorLightInactive)
#pragma config(Sensor, S3,     lightSensor2,   sensorLightInactive)
#pragma config(Motor,  motorA,          Rotation,      tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          Lid,           tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          LidAngle,      tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
     wait10Msec(500);

// Stop the motor and reset the angle indicator's opinion about the motor position so we can run it up to open the lid
motor[Lid] = 0;
nMotorEncoder[LidAngle] = 0;

   while( true )
   {
     wait1Msec(100);
     // By default, stop the rotation motor, we'll turn it on briefly if needed
     motor[Rotation] = 0;
     nxtDisplayBigTextLine( 1, "1: %d", SensorValue[lightSensor1] );
     nxtDisplayBigTextLine( 3, "2: %d", SensorValue[lightSensor2] );
     nxtDisplayBigTextLine( 5, "Lid: %d", nMotorEncoder[LidAngle] );
     if (SensorValue[lightSensor1] - SensorValue[lightSensor2] > 10 )
     {
       // Turn one way, it's brighter over here
      motor[Rotation] = 20;
     }
     if (SensorValue[lightSensor2] - SensorValue[lightSensor1] > 10 )
     {
       // Turn the other way, it's brighter over there
      motor[Rotation] = -20;
     }

     if ( SensorValue[lightSensor1] + SensorValue[lightSensor2] > 50 )
     {
       if( nMotorEncoder[LidAngle] > -65 )
       {
       motor[Lid] = 10;
       }
       else
       {
       motor[Lid] = 0;
       }
     }

     // Deal with overly bright light by closing to between -34 and -36 degrees
     if ( SensorValue[lightSensor1] + SensorValue[lightSensor2] > 150 )
     {
       if( nMotorEncoder[LidAngle] > -36 )
       {
       motor[Lid] = 5;
       }
       else if( nMotorEncoder[LidAngle] < -34 )
       {
       motor[Lid] = -5;
       }
       else
       {
         motor[Lid] = 0;
       }
     }

     if ( SensorValue[lightSensor1] + SensorValue[lightSensor2] < 25 )
     {
       if( nMotorEncoder[LidAngle] < -5 )
	     {
	       motor[Lid] = -10;
	     }
	     else
	     {
	       motor[Lid] = 0
	     }
     }
 }

   motor[motorA] = 0;                     // Motor C is stopped with a 0 power level.
   motor[motorB] = 0;                     // Motor C is stopped with a 0 power level.
   motor[motorC] = 0;                     // Motor B is stopped with a 0 power level.
}
